version: "3.7"

services:
  #kometa:
  #  image: lscr.io/linuxserver/kometa:latest
  #  container_name: kometa
  #  env_file: .env
  #  volumes:
  #    - ./config:/config:rw
  #  restart: always
  kometa_randomizer:
    container_name: kometa_randomizer
    build: .
    env_file: .env
    volumes:
      - ./config:/config:rw
    restart: always