version: "3.7"

services:
  kometa:
    image: lscr.io/linuxserver/kometa:latest
    container_name: kometa
    env_file: .env
    volumes:
      - /volume1/docker/kometa/config:/config:rw
    restart: always
