FROM alpine:3.18

RUN apk add --no-cache bash tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./source/randomizer.sh /usr/local/bin/randomizer.sh

RUN chmod +x /usr/local/bin/randomizer.sh

ENTRYPOINT ["/usr/local/bin/randomizer.sh"]
